services:
  devcontainer:
    environment:
      - EDIRECT_LOCAL_ARCHIVE=${DATA_PATH}/Archive
      - NCBI_API_KEY=${NCBI_API_KEY}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/root/.ssh:cached
      - ~/.gitconfig:/root/.gitconfig:cached
      - ~/.wakatime.cfg:/root/.wakatime.cfg:cached
      - ~/.cache:/root/.cache:cached
      - ${DATA_PATH}:/data:cached
    command: sleep infinity
