version: '3.8'
services:
  devcontainer:
    environment:
      - EDIRECT_LOCAL_ARCHIVE=/workspaces/data/Archive
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/root/.ssh:cached
      - ~/.gitconfig:/root/.gitconfig:cached
      - ~/.wakatime.cfg:/root/.wakatime.cfg:cached
      - ~/.cache:/root/.cache:cached
      - /data/bioin-401-project:/data:cached
    command: sleep infinity
